In [ ]:
expenses = [1138,101,12,300,2049]
print(sum(expenses))
#串列相加

3600


In [ ]:
expenses = [1138,101,12,300,2049,5461,2122]
print(expenses[0]) #索引從0開始
print(expenses[1])
print(expenses[-4]) #倒數第四個
print(expenses[-2]) #倒數第二個

1138
101
300
5461


In [ ]:
my_list0 = [] #空串列
my_list1 = list() 
my_list2 = ['python', 'javascript', 'C#']
print(my_list2[-1]) #串列2倒數第一個元素

C#


In [ ]:
my_list2 = ['python', 'javascript', 'C#']
print(len(my_list2)) #串列2的長度
print(len(my_list2[0])) #串列2第一個元素的長度

3
6


In [ ]:
my_list2 = ['python', 'javascript', 'C#']
my_list2.append('java') #將java附加至串列2
print(my_list2)

['python', 'javascript', 'C#', 'java']


In [ ]:
my_list2 = ['python', 'javascript', 'C#']
my_list2.insert(2,'java')
print(my_list2) #將java插入至串列2第三個

['python', 'javascript', 'java', 'C#']


In [ ]:
my_list2 = ['python', 'javascript', 'C#']
my_list2.remove('javascript') #移除指定元素javascript
print(my_list2)
del my_list2[-1] #刪除指定位置的元素
print(my_list2)
my_list2.clear() #清除全部
print(my_list2)

['python', 'C#']
['python']
[]


In [ ]:
a=[1,2]
print(a*5) #五倍的串列a

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]


In [ ]:
a=[1,2,3,4,5,6,7,8,9,10,11.12]
b=a[0:4] #範圍取值,0,1,2,3不包含4
print(b)
c=a[0:12:3] #間隔3取值 
print(c)
d=a[2: ] #取2-11
print(d)
e=a[ :9] #取0-8
print(e)
f=a[:] #取全部值
print(f)

[1, 2, 3, 4]
[1, 4, 7, 10]
[3, 4, 5, 6, 7, 8, 9, 10, 11.12]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11.12]


In [ ]:
a=[3,7,9,12,5,2,100,277,20,16,18,13,52,513]
del a[6:8] #刪除某範圍值,6,7
print(a)
print(min(a)) #最小值
print(max(a)) #最大值
print(a.index(12)) #找出12所在的第一個索引值
b=[13,20,79,13,56,14,13,13,20,13]
print(b.count(13)) #13出現的次數
a.reverse( ) #串列反轉
print(a)
a.sort( )  #串列由小到大排序,a的值會被改變
print(a)

[3, 7, 9, 12, 5, 2, 20, 16, 18, 13, 52, 513]
2
513
3
5
[513, 52, 13, 18, 16, 20, 2, 5, 12, 9, 7, 3]
[2, 3, 5, 7, 9, 12, 13, 16, 18, 20, 52, 513]


In [ ]:
expenses = [15441,204,13,579,150,77]
s=sorted(expenses) #expenses的值不會變
print(s,expenses)

[13, 77, 150, 204, 579, 15441] [15441, 204, 13, 579, 150, 77]


In [ ]:
a_tuple=('python', 'js', 'SQL')
print(a_tuple)
b_list=['go', 'c#', 'vb']
b_tuple=tuple(b_list)
print(b_tuple)
print(b_tuple[0])

('python', 'js', 'SQL')
('go', 'c#', 'vb')
go


In [ ]:
languages = {}
languages = {'name':'python', 'version':'3.7'} #索引值(鍵值)可以自訂
print(languages['name'])
print(languages['version'])
a={0:'python', 1:'java', 2:'SQL'}
print(a[0])
print(a[1])
print(a[2])
print(languages)
print(languages.keys())
print(languages.values())
print(languages.items())
print('name' in languages)

python
3.7
python
java
SQL
{'name': 'python', 'version': '3.7'}
dict_keys(['name', 'version'])
dict_values(['python', '3.7'])
dict_items([('name', 'python'), ('version', '3.7')])
True


In [ ]:
a_list=[1,2,3,4,5]
print(a_list*3) #三倍的串列a

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
#numpy套件的ndarray型態,提供element-wise的操作
import numpy as np
a=np.array([1,2,3,4,5])
print(a*3) #串列a數值乘以3

[ 3  6  9 12 15]


In [ ]:
a=np.array([1,2,3,4,105,200])
print(type(a))
print(a.shape) #ndaary的形狀
print(a.dtype) #資料的型態
print(a.ndim) #維度

<class 'numpy.ndarray'>
(6,)
int64
1


In [ ]:
import numpy as np
z=np.zeros(6)
print(z)
print(np.empty((2,3,4)))
print(np.arange(10))

[0. 0. 0. 0. 0. 0.]
[[[1.30467164e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
my_array=np.arange(20)
print(my_array)
print(my_array[15])
print(my_array[0:12]) #取0-12

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
15
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:])
print(my_2d_array[:,4])
print(my_2d_array[1,1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[4 9]
6


In [ ]:
my_array=np.arange(0,10)
print(my_array)
print(my_array.shape)
my_2d_array=my_array.reshape(2,5)
print(my_2d_array)
print((np.arange(0,100).reshape(10,10)))

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
b=np.array([56,10,22,13,113,np.nan])
print(b)

[ 56.  10.  22.  13. 113.  nan]


In [ ]:
import math
radius = eval(input("請輸入圓的半徑：")) #把輸入的字串變成數學計算型態
print("圓的面積為：", radius * radius * math.pi)

請輸入圓的半徑：20
圓的面積為： 1256.6370614359173


In [ ]:
import math
def circle_area(radius):
    area = radius * radius * math.pi
    return area

print(circle_area(15)) #半徑15的圓面積

706.8583470577034


In [ ]:
import os
print(os.getcwd()) #顯示目前所在的工作目錄

/content


In [ ]:
#顯示目錄下的檔案
os.listdir(".")

['.config', 'sample_data']

In [ ]:
#新增目錄
os.makedirs("test")
os.listdir(".")

['.config', 'test', 'sample_data']

In [ ]:
#移除目錄
os.rmdir("test")
os.listdir(".")

['.config', 'sample_data']

In [ ]:
a=open("a.txt","w") #新增檔案
a.write("This is a test1")
a.write("This is a test2\n")
a.write("This is a test3\n")
a.close() #關閉檔案

In [ ]:
#檢查檔案是否存在
os.path.isfile("a.txt")

True

In [ ]:
#讀取檔案
a=open("a.txt","r")
print(a.readline())
print(a.readline())
print(a.readline()) #多餘的命令，檔案只有2行
a.close()

This is a test1This is a test2

This is a test3




In [ ]:
a=open("a.txt","r")
print(a.readlines())  #一次讀取多行，與a.read()命令相同
a.close()

['This is a test1This is a test2\n', 'This is a test3\n']


In [ ]:
#加上檔案是否存在的判斷
if os.path.isfile("a.txt"):
    a=open("a.txt","r")
    print(a.readlines())
    a.close()
else:
    print("檔案不存在")

['This is a test1This is a test2\n', 'This is a test3\n']


In [ ]:
#split函式
if os.path.isfile("a.txt"):
    a=open("a.txt","r")
    for line in a:
        fields=line.split(" ") #以空白為切割欄位
        print(fields)
    a.close()
else:
    print("檔案不存在")

['This', 'is', 'a', 'test1This', 'is', 'a', 'test2\n']
['This', 'is', 'a', 'test3\n']


In [ ]:
#附加檔案
a=open("a.txt", "a")
a.write("This is test4\n")
a.close()
a=open("a.txt","r")
print(a.readlines())
a.close()

['This is a test1This is a test2\n', 'This is a test3\n', 'This is test4\n']


In [ ]:
a=open("a.txt","r+")
a.write("This is a test5\n")
a.close()
a=open("a.txt","r")
print(a.readlines())
a.close()

['This is a test5\n', 'his is a test2\n', 'This is a test3\n', 'This is test4\n']


In [ ]:
#刪除檔案
if os.path.isfile("a.txt"):
    os.remove("a.txt")
    print("檔案刪除成功")
else:
    print("找不到檔案")
print(os.path.isfile("a.txt"))

檔案刪除成功
False


In [ ]:
a=10
b=20
if a<b:
    print(n)

NameError: ignored

In [ ]:
a=10
b=20
try:
    if a<b:
        print(n)
except:
    print("錯誤產生")

錯誤產生


In [ ]:
#指定錯誤類別處理
a=10
b=20
try:
    if a<b:
        print(n)
except NameError as e:
    print("錯誤產生, 錯誤原因：",e)
except ZeroDivisionError:
    print("除以0錯誤")

錯誤產生, 錯誤原因： name 'n' is not defined


In [ ]:
a=10
b=20
try:
    if a>b: #改變比較條件，讓錯誤不發生
        print(n)
except:
    print("錯誤發生")
else:
    print("沒有錯誤發生時會執行的部分")

沒有錯誤發生時會執行的部分


In [ ]:
a=10
b=20
try:
    if a>b: #改變比較條件，讓錯誤不發生
        print(n)
except:
    print("錯誤發生")
else:
    print("沒有錯誤發生時會執行的部分")
finally:
    print("不管有沒有錯誤一定會執行的部分")

沒有錯誤發生時會執行的部分
不管有沒有錯誤一定會執行的部分
